[build]
  command = "npm run build"
  publish = "build"
  functions = "functions-build"

[functions]
  external_node_modules = ["ws"]
  node_bundler = "esbuild"

[build.environment]
  NODE_VERSION = "18"