[build]
  command = "npm run build"
  publish = ".netlify/build"
  functions = "netlify/functions"

[functions]
  external_node_modules = ["ws"]
  node_bundler = "esbuild"

[build.environment]
  NODE_VERSION = "18"