[build]
  command = "npm run build"
  functions = "netlify/functions"
  publish = "build"

[functions]
  node_bundler = "esbuild"

[[redirects]]
  from = "/.netlify/functions/websocket/*"
  to = "/.netlify/functions/websocket/:splat"
  status = 200
  force = true
  conditions = { Role = "system" }